Resolve win32 build Error C2440 with CALLBACK function decoration
'function': cannot convert from 'void (__cdecl *)(PVOID,BOOLEAN)' to 'WAITORTIMERCALLBACK'